#!/usr/bin/env python3
"""Analyze 2-node jacobi sweep CSV → markdown report."""

import csv
import statistics
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RESULTS = REPO / "repro" / "jacobi" / "results"


def latest_csv() -> Path:
    cands = sorted(RESULTS.glob("results-2node-*.csv"))
    assert cands, f"No results-2node-*.csv in {RESULTS}"
    return cands[-1]


def main(argv: list[str]) -> None:
    path = Path(argv[1]) if len(argv) > 1 else latest_csv()
    rows = list(csv.DictReader(path.open()))
    assert rows, f"empty CSV: {path}"

    by = defaultdict(list)
    for r in rows:
        if not r["runtime_s"]:
            continue
        key = (r["sweep"], r["variant"], int(r["nx"]), int(r["num_gpus"]))
        by[key].append(float(r["runtime_s"]))

    def fmt(seq: list[float]) -> str:
        if not seq:
            return "—"
        m = statistics.mean(seq)
        s = statistics.stdev(seq) if len(seq) > 1 else 0.0
        return f"{m:.3f} ± {s:.3f}"

    out: list[str] = []
    out.append(f"# 2-node Jacobi reproduction — {path.name}\n")
    out.append("Generated by `repro/jacobi/analyze_2node.py`. Times are mean ± stdev (s).\n")

    out.append("## Sweep A2 — scale-up at nx=ny=16384, niter=1000, 2 nodes\n")
    gpus = sorted({int(r["num_gpus"]) for r in rows})
    variants_a = ["nccl", "nccl_graphs", "nvshmem", "nvshmem_block", "nvshmem_block_nbsync"]
    out.append("| Variant | " + " | ".join(f"{g} GPU total" for g in gpus) + " |")
    out.append("|" + "---|" * (len(gpus) + 1))
    for v in variants_a:
        cells = []
        for g in gpus:
            seq = by.get(("A2", v, 16384, g), [])
            cells.append(fmt(seq))
        out.append(f"| {v} | " + " | ".join(cells) + " |")
    out.append("")

    out.append("## Sweep B2 — nx axis, 2 nodes\n")
    variants_b = ["nccl", "nccl_graphs", "nvshmem_block_nbsync"]
    nxs = sorted({int(r["nx"]) for r in rows if r["sweep"] == "B2"})
    if nxs:
        out.append("| Variant | " + " | ".join(f"nx={nx}" for nx in nxs) + " |")
        out.append("|" + "---|" * (len(nxs) + 1))
        for v in variants_b:
            cells = []
            for nx in nxs:
                gpn_cells = []
                for g in gpus:
                    seq = by.get(("B2", v, nx, g), [])
                    if seq:
                        gpn_cells.append(fmt(seq))
                cells.append(gpn_cells[0] if gpn_cells else "—")
            out.append(f"| {v} | " + " | ".join(cells) + " |")
        out.append("")

    out.append("## Headline (16384², niter=1000, 2 nodes)\n")
    for v in ("nccl", "nccl_graphs", "nvshmem", "nvshmem_block", "nvshmem_block_nbsync"):
        for g in gpus:
            seq = by.get(("A2", v, 16384, g), [])
            if seq:
                out.append(f"* **{v}** @ {g} GPU: {fmt(seq)} s")
    out.append("")

    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv)
