#!/usr/bin/env python3
"""Analyze 1-node jacobi sweep CSV → markdown report.

Usage: python3 repro/jacobi/analyze.py [results-1node-*.csv]
       (defaults to the newest results-1node-*.csv in repro/jacobi/results/)
"""

import csv
import statistics
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RESULTS = REPO / "repro" / "jacobi" / "results"


def latest_csv() -> Path:
    cands = sorted(RESULTS.glob("results-1node-*.csv"))
    assert cands, f"No results-1node-*.csv in {RESULTS}"
    return cands[-1]


def main(argv: list[str]) -> None:
    path = Path(argv[1]) if len(argv) > 1 else latest_csv()
    rows = list(csv.DictReader(path.open()))
    assert rows, f"empty CSV: {path}"

    # Note: an early bug wrote `extra=block,nbsync` unquoted so DictReader split
    # it across two fields. Key off (sweep, variant, nx, num_gpus) only — the
    # variant name encodes everything we need.
    by = defaultdict(list)
    for r in rows:
        if not r["runtime_s"]:
            continue
        key = (r["sweep"], r["variant"], int(r["nx"]), int(r["num_gpus"]))
        by[key].append(float(r["runtime_s"]))

    def fmt(seq: list[float]) -> str:
        m = statistics.mean(seq)
        s = statistics.stdev(seq) if len(seq) > 1 else 0.0
        return f"{m:.3f} ± {s:.3f}"

    out: list[str] = []
    out.append(f"# 1-node Jacobi reproduction — {path.name}\n")
    out.append("Generated by `repro/jacobi/analyze.py`. Times are mean ± stdev (s) over reps.\n")

    out.append("## Sweep A — scale-up at nx=ny=16384, niter=1000\n")
    variants_a = ["single_gpu", "mpi", "mpi_overlap", "nccl", "nccl_overlap",
                  "nccl_graphs", "nvshmem", "nvshmem_block", "nvshmem_block_nbsync"]
    gpus_a = [1, 2, 4, 8]
    out.append("| Variant | " + " | ".join(f"{g} GPU" for g in gpus_a) + " |")
    out.append("|" + "---|" * (len(gpus_a) + 1))
    for v in variants_a:
        cells = []
        for g in gpus_a:
            seq = by.get(("A", v, 16384, g), [])
            cells.append(fmt(seq) if seq else "—")
        out.append(f"| {v} | " + " | ".join(cells) + " |")
    out.append("")

    out.append("## Sweep B — nx axis at 8 GPU, ny=16384, niter=1000\n")
    variants_b = ["nccl", "nccl_graphs", "nvshmem", "nvshmem_block_nbsync"]
    nxs_b = [2048, 4096, 8192, 16384]
    out.append("| Variant | " + " | ".join(f"nx={nx}" for nx in nxs_b) + " |")
    out.append("|" + "---|" * (len(nxs_b) + 1))
    for v in variants_b:
        cells = []
        for nx in nxs_b:
            seq = by.get(("B", v, nx, 8), [])
            cells.append(fmt(seq) if seq else "—")
        out.append(f"| {v} | " + " | ".join(cells) + " |")
    out.append("")

    out.append("## Headline numbers (8 GPU, 16384², 1000 iter)\n")
    for v in ("nccl", "nccl_graphs", "nvshmem", "nvshmem_block_nbsync"):
        seq = by.get(("A", v, 16384, 8), [])
        if seq:
            out.append(f"* **{v}**: {fmt(seq)} s  (n={len(seq)}, min={min(seq):.3f}, max={max(seq):.3f})")
    out.append("")

    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv)
